name: Autograde Python Assignment

on:
  push:
    branches:
      - main

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run autograder
        run: python autograde.py

      - name: Upload results
        run: |
          echo "Student ID: ${{ github.actor }}" >> results.txt
          cat autograde_results.txt >> results.txt
        continue-on-error: true
        if: always()

      - name: Commit results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add results.txt
          git commit -m "Add autograding results"
          git push
        if: success()
