name: Autograde Python Assignment

on:
  push:
    branches:
      - main

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Debugging Information
        run: |
          echo "Python Version:"
          python --version
          echo "Installed Packages:"
          pip list
          echo "Current Directory:"
          pwd
          echo "List of Files:"
          ls -la

      - name: Create results directory
        run: |
          echo "Creating results directory..."
          mkdir -p results
          ls -la

      - name: Run tests and collect results
        run: |
          echo "Running tests..."
          pytest -v || echo "Pytest failed"
          ls -la results
          cat results/test_output.txt || echo "No test output found"

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results/
