name: Autograde Python Assignment

on:
  push:
    branches:
      - main

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Debugging Information
        run: |
          echo "Python Version:"
          python --version
          echo "Installed Packages:"
          pip list

      - name: Run tests and collect results
        run: |
          mkdir -p results
          pytest -v > results/test_output.txt

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results/
